version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  pytest_test:
    build:
      dockerfile: DockerfilePytest
      context: .
    depends_on:
      - web
  postman_test:
    build:
      dockerfile: DockerfilePostman
      context: .
    depends_on:
      - web
